"""empty message

Revision ID: 1270c7ec93f4
Revises: bae7edcf6d47
Create Date: 2022-11-29 09:57:44.034965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1270c7ec93f4'
down_revision = 'bae7edcf6d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks_tipster', schema=None) as batch_op:
        batch_op.alter_column('units',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=5),
               existing_nullable=False)

    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['img'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('picks_tipster', schema=None) as batch_op:
        batch_op.alter_column('units',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
