"""empty message

Revision ID: b0cfab2f5a18
Revises: 
Create Date: 2022-04-28 10:00:24.668207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cfab2f5a18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(length=20), nullable=False),
    sa.Column('dia', sa.String(length=8), nullable=False),
    sa.Column('mes', sa.String(length=5), nullable=False),
    sa.Column('year', sa.String(length=5), nullable=False),
    sa.Column('h1', sa.String(length=90), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('h2', sa.String(length=90), nullable=False),
    sa.Column('desarrollo1', sa.TEXT(length=30000), nullable=False),
    sa.Column('h3', sa.String(length=90), nullable=False),
    sa.Column('desarrollo2', sa.TEXT(length=30000), nullable=False),
    sa.Column('h4', sa.String(length=90), nullable=False),
    sa.Column('desarrollo3', sa.TEXT(length=30000), nullable=False),
    sa.Column('h5', sa.String(length=90), nullable=False),
    sa.Column('desarrollo4', sa.TEXT(length=30000), nullable=False),
    sa.Column('h6', sa.String(length=90), nullable=False),
    sa.Column('desarrollo5', sa.TEXT(length=30000), nullable=False),
    sa.Column('imagen_principal', sa.String(length=90), nullable=False),
    sa.Column('imagen_secundaria_1', sa.String(length=90), nullable=False),
    sa.Column('imagen_secundaria_2', sa.String(length=90), nullable=False),
    sa.Column('imagen_secundaria_3', sa.String(length=90), nullable=False),
    sa.Column('video_1', sa.String(length=90), nullable=False),
    sa.Column('video_2', sa.String(length=90), nullable=False),
    sa.Column('enlace_1', sa.String(length=150), nullable=False),
    sa.Column('enlace_2', sa.String(length=150), nullable=False),
    sa.Column('enlace_3', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(length=20), nullable=False),
    sa.Column('mail', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('noticias')
    # ### end Alembic commands ###
