"""empty message

Revision ID: c18208c427dd
Revises: 
Create Date: 2022-11-29 10:23:28.778144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18208c427dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_tipster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picks_tipster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('units', sa.String(length=20), nullable=False),
    sa.Column('deporte', sa.String(length=40), nullable=False),
    sa.Column('equipos', sa.String(length=500), nullable=False),
    sa.Column('linea', sa.String(length=500), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('resultado', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=500), nullable=False),
    sa.Column('like', sa.String(length=20), nullable=False),
    sa.Column('dislike', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.String(length=1500), nullable=False),
    sa.Column('usuario', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('mail', sa.String(length=50), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('born', sa.String(length=50), nullable=False),
    sa.Column('subscription', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('upload')
    op.drop_table('picks_tipster')
    op.drop_table('perfil_tipster')
    # ### end Alembic commands ###
